//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesClient.ServicesAtAGlance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesAtAGlance.OurWebService1Soap")]
    public interface OurWebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServicesClient.ServicesAtAGlance.HelloWorldResponse HelloWorld(WebServicesClient.ServicesAtAGlance.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.HelloWorldResponse> HelloWorldAsync(WebServicesClient.ServicesAtAGlance.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        WebServicesClient.ServicesAtAGlance.MessageResponse Message(WebServicesClient.ServicesAtAGlance.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.MessageResponse> MessageAsync(WebServicesClient.ServicesAtAGlance.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Squareroot", ReplyAction="*")]
        float Squareroot(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Squareroot", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SquarerootAsync(float f);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesClient.ServicesAtAGlance.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServicesClient.ServicesAtAGlance.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesClient.ServicesAtAGlance.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServicesClient.ServicesAtAGlance.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesClient.ServicesAtAGlance.MessageRequestBody Body;
        
        public MessageRequest() {
        }
        
        public MessageRequest(WebServicesClient.ServicesAtAGlance.MessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public MessageRequestBody() {
        }
        
        public MessageRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesClient.ServicesAtAGlance.MessageResponseBody Body;
        
        public MessageResponse() {
        }
        
        public MessageResponse(WebServicesClient.ServicesAtAGlance.MessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageResult;
        
        public MessageResponseBody() {
        }
        
        public MessageResponseBody(string MessageResult) {
            this.MessageResult = MessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OurWebService1SoapChannel : WebServicesClient.ServicesAtAGlance.OurWebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OurWebService1SoapClient : System.ServiceModel.ClientBase<WebServicesClient.ServicesAtAGlance.OurWebService1Soap>, WebServicesClient.ServicesAtAGlance.OurWebService1Soap {
        
        public OurWebService1SoapClient() {
        }
        
        public OurWebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OurWebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OurWebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OurWebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesClient.ServicesAtAGlance.HelloWorldResponse WebServicesClient.ServicesAtAGlance.OurWebService1Soap.HelloWorld(WebServicesClient.ServicesAtAGlance.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServicesClient.ServicesAtAGlance.HelloWorldRequest inValue = new WebServicesClient.ServicesAtAGlance.HelloWorldRequest();
            inValue.Body = new WebServicesClient.ServicesAtAGlance.HelloWorldRequestBody();
            WebServicesClient.ServicesAtAGlance.HelloWorldResponse retVal = ((WebServicesClient.ServicesAtAGlance.OurWebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.HelloWorldResponse> WebServicesClient.ServicesAtAGlance.OurWebService1Soap.HelloWorldAsync(WebServicesClient.ServicesAtAGlance.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.HelloWorldResponse> HelloWorldAsync() {
            WebServicesClient.ServicesAtAGlance.HelloWorldRequest inValue = new WebServicesClient.ServicesAtAGlance.HelloWorldRequest();
            inValue.Body = new WebServicesClient.ServicesAtAGlance.HelloWorldRequestBody();
            return ((WebServicesClient.ServicesAtAGlance.OurWebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesClient.ServicesAtAGlance.MessageResponse WebServicesClient.ServicesAtAGlance.OurWebService1Soap.Message(WebServicesClient.ServicesAtAGlance.MessageRequest request) {
            return base.Channel.Message(request);
        }
        
        public string Message(string username) {
            WebServicesClient.ServicesAtAGlance.MessageRequest inValue = new WebServicesClient.ServicesAtAGlance.MessageRequest();
            inValue.Body = new WebServicesClient.ServicesAtAGlance.MessageRequestBody();
            inValue.Body.username = username;
            WebServicesClient.ServicesAtAGlance.MessageResponse retVal = ((WebServicesClient.ServicesAtAGlance.OurWebService1Soap)(this)).Message(inValue);
            return retVal.Body.MessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.MessageResponse> WebServicesClient.ServicesAtAGlance.OurWebService1Soap.MessageAsync(WebServicesClient.ServicesAtAGlance.MessageRequest request) {
            return base.Channel.MessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesClient.ServicesAtAGlance.MessageResponse> MessageAsync(string username) {
            WebServicesClient.ServicesAtAGlance.MessageRequest inValue = new WebServicesClient.ServicesAtAGlance.MessageRequest();
            inValue.Body = new WebServicesClient.ServicesAtAGlance.MessageRequestBody();
            inValue.Body.username = username;
            return ((WebServicesClient.ServicesAtAGlance.OurWebService1Soap)(this)).MessageAsync(inValue);
        }
        
        public float Squareroot(float f) {
            return base.Channel.Squareroot(f);
        }
        
        public System.Threading.Tasks.Task<float> SquarerootAsync(float f) {
            return base.Channel.SquarerootAsync(f);
        }
    }
}
