//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDummy
    {
        public int Empno { get; set; }
        public string EName { get; set; }
        public Nullable<int> EAge { get; set; }
        public string ECity { get; set; }
        public string EPhone { get; set; }
        public Nullable<int> EDeptid { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
