//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table1
    {
        public int TId { get; set; }
        public string TName { get; set; }
        public string TGrade { get; set; }
        public Nullable<int> TPercentage { get; set; }
        public string newcol { get; set; }
    }
}
